# 开发环境配置
server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: "123456"
  # TODO 解决运行springboot时修改静态资源不实时更新
  thymeleaf:
    cache: false # 关闭 Thymeleaf 模板引擎缓存
  # redis 相关配置
  redis:
    host: localhost
    port: 6379
    #password: 123456
    database: 1
  cache:
    redis:
      # 设置缓存数据的过期时间（单位：毫秒）
      time-to-live: 3600000
  # 热部署相关配置（开启）
  devtools:
    restart:
      enabled: true
      exclude: backend/**,front/**,application-dev.yml,application-dev.yml,application-pro.yml
# TODO 上传文件储存位置
reggie:
  path: E:\BaiduNetdiskDownload\reggie_img\