# 生产环境配置
server:
  port: 8088
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.100.66:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  # redis 相关配置
  redis:
    host: 192.168.100.66
    port: 6379
    password: 123456
    database: 0
  cache:
    redis:
      time-to-live: 3600000
  # 热部署相关配置（关闭）
  devtools:
    restart:
      enabled: false
# TODO 上传文件储存位置
reggie:
  path: /root/java_apps/img